// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PalletBalancer.Api.Data;

#nullable disable

namespace PalletBalancer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PalletBalancer.Api.Models.Fdo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Consignee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DsbDate")
                        .HasColumnType("date");

                    b.Property<string>("FdoSlipNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ShipDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Fdos");
                });

            modelBuilder.Entity("PalletBalancer.Api.Models.FdoLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerPoNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FdoId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemModelNo")
                        .HasColumnType("text");

                    b.Property<string>("ModelNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReqQty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FdoId");

                    b.HasIndex("ItemModelNo");

                    b.ToTable("FdoLineas");
                });

            modelBuilder.Entity("PalletBalancer.Api.Models.Item", b =>
                {
                    b.Property<string>("ModelNo")
                        .HasColumnType("text");

                    b.Property<double>("CajaAltoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("CajaAnchoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("CajaLargoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("CajaPesoKg")
                        .HasColumnType("double precision");

                    b.Property<int>("CajaPiezasPorCaja")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PiezaAltoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("PiezaAnchoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("PiezaLargoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("PiezaPesoKg")
                        .HasColumnType("double precision");

                    b.Property<double>("SpAltoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("SpAnchoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("SpLargoCm")
                        .HasColumnType("double precision");

                    b.Property<double>("SpPesoKg")
                        .HasColumnType("double precision");

                    b.Property<int>("SpPiezasPorPallet")
                        .HasColumnType("integer");

                    b.Property<bool>("PuedeEstibar")
                        .HasColumnType("boolean");

                    b.HasKey("ModelNo");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PalletBalancer.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PalletBalancer.Api.Models.FdoLinea", b =>
                {
                    b.HasOne("PalletBalancer.Api.Models.Fdo", "Fdo")
                        .WithMany("Lineas")
                        .HasForeignKey("FdoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PalletBalancer.Api.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemModelNo");

                    b.Navigation("Fdo");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PalletBalancer.Api.Models.Fdo", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
